### ISSUE TITLE
Live Ping of server

### ISSUE THREAD

**Issue by EldonMcGuinness** [ITRav4/PlexRedirect#1]
Have you considered doing a ping of the plex server on the plex port to see if the server is available then letting that change the image as needed?

On fail it could give a red screen and on success it could be the green one; while waiting the screen could be yellow.

ping via JS
https://github.com/alfg/ping.js

**Comment by ITRav4** [comment]
I tried to implement this but was unable to configure it. It would be a great idea though. I've added a server offline image to the assets if you want to give it a shot.

**Comment by EldonMcGuinness** [comment]
Perhaps try something like this as it seems to be working for me. Do note that the second one does eventually timeout and say down, this can take a minute though.

Since the plex server is there it will return an error which is good enough for it to trigger an up status.

http://jsfiddle.net/EldonMcGuinness/gcgww53p/1/

**Comment by ITRav4** [comment]
I don't have time to work on this right now. I wouldn't mind if you want to go ahead and contribute by creating a pull request. If not, I will work on it over the weekend and update you here.

**Comment by EldonMcGuinness** [comment]
I just added a PR to the ping.js dev's branch as I added a timeout option to it. This will make the server come back as down if the time it takes exceeds a specified interval. You can find the updated JS in his repo [here](https://github.com/alfg/ping.js/blob/master/src/ping.js)

You can see it in action with this [fiddle](http://jsfiddle.net/EldonMcGuinness/gcgww53p/5/):

**Comment by cwire4** [comment]
I've been working on some PHP by modifing the orignal template a tiny bit.  All it's doing now is check the server status by using the Plex API as well as mapping the libraries and their keys.  I'm also hiding the navbar if it's down so the only thing that shows up is the error image.  It's admittedly kind of hacked together at the moment as I just wanted to get something simple together.  It can take a while to load if the library is large, though because of the large xml responses.  Haven't found a lightweight method to get the library counts without going to http://server:32400/library/sections/<sectionID>/all  Any interest in that?

**Comment by EldonMcGuinness** [comment]
Hiding the navbar would be easy with the addition of the ping script in this PR, but I think displaying counts and the like are a bit much for a page that is not login protected. I would rather save that for the user to see once they have logged in.

---

Added the hiding of the link bar when the server is down to the commit. @ITRav4 feel free to use which ever commit you like.

You can see the effects here:
http://eldonmcguinness.github.io/PlexRedirect/up.html
http://eldonmcguinness.github.io/PlexRedirect/down.html

In either case, I would suggest a yellow intermediary image be created to be shown during the checking phase of the script, this way the first image seen is not that ominous red one. :D

**Comment by ITRav4** [comment]
@EldonMcGuinness I've added your code to the git and a new orange checking img. Thank you for your help. If you could just add the orange img now I would really appreciate it.

**Comment by ITRav4** [comment]
@cwire4 Like @EldonMcGuinness said, I don't think displaying that type of info without a protected website is ideal. Since this website is technically only for users, they can see that info once they log in to their Plex account.

**Comment by EldonMcGuinness** [comment]
@ITRav4 done
