### ISSUE TITLE
What to do when Plex Redirect and Plex Media Server are on different machines?

### ISSUE THREAD

**Issue by CKyle22** [ITRav4/PlexRedirect#13]
I have an ngnix server running on a Raspberry Pi that's configured to work with a domain name. My Plex server is on the same network with a local ip of 192.168.1.15. Obviously though, if I'm not connected to my local network when I go to my domain, it shows Plex as down and unreachable. How can I fix this? I don't want to install Plex on my RPi, and I don't want to have my public IP viewable in the source code.

Relevant section of index.html.

`
            var server = "192.168.1.15" //Try to get it automagically, but you can manually specify this
            var timeout = 2000; //Milliseconds
            var body = document.getElementsByTagName("body")[0];
            p.ping(server+":32400", function(data) {`

**Comment by ITRav4** [comment]
You can use a DDNS service like NoIP.
