### ISSUE TITLE
Ping never resolving?

### ISSUE THREAD

**Issue by justinerwin** [ITRav4/PlexRedirect#16]
When navigating to my Plex landing page, the ping process never resolves, good or bad. I know the server is up and accessible from the outside network, and I know that the IP address/port is correct and open. What should I do next?

**Comment by ITRav4** [comment]
Could you send me the part where you modified with your IP address? You can replace the IP address and port with a fake one, but I want to see if it's all in place.

**Comment by justinerwin** [comment]
![screen shot 2016-10-24 at 1 12 38 pm](https://cloud.githubusercontent.com/assets/21181706/19655908/9ba2e4d8-99eb-11e6-8c99-734395bde151.png)
So, this is what the code looks like now for the ping function. I had to go down further in the HTML and remove the actual layout below the Plex, request, and email buttons, and I comment'd out the "onload" in the first <body> so I could at least get the homepage to work. I have a duckDNS name for my public IP as well, but it didn't work with that, with my ip address, or the document.domain.

NOTE: It only seemed to be an issue from inside my LAN. I turned my cell phone's wifi off and was able to get it to work, ONCE. but then I got the same error.

**Comment by ITRav4** [comment]
document.domain should have " ". 

Ex: "document.domain" 
Ex2: "192.168.1.1"
Ex3: var server = "duckDNS.mywebpage.com"

Add your external IP address there with a port or use your duckDNS webpage and see if that works. Sorry it has taken time to reply. I've been away for a while but I'm back now.

**Comment by ITRav4** [comment]
@justinerwin did you get it to work?

**Comment by ITRav4** [comment]
I'm closing this issue as I've gotten no response. If you need any further assistance my email is rav4it@gmail.com
