### ISSUE TITLE
Disable ping.js

### ISSUE THREAD

**Issue by yeyeoke** [ITRav4/PlexRedirect#17]
Hi, as my knowledge of html is far worse than 'limited' I thought I'd ask here, is it possible to disable the checking and jump straight to the mainpage and simply show it as "online". As I'm running my webserver on my plexserver there is really no need to check if its up. Is there a simple line of code I can change or something?

**Comment by yeyeoke** [comment]
Nevermind, I found that your 1.0 release didnt check but instead just showed a static page, exactly what I was looking for.

**Comment by ITRav4** [comment]
@yeyeoke Glad you got it working.
