### ISSUE TITLE
[Suggestion] Use PlexPy server down/up tricker for Plex Status

### ISSUE THREAD

**Issue by ghost** [ITRav4/PlexRedirect#3]
I would suggest looking into using the PlexPy tricker for tracker server up or down as you can now make your own custom scripts. This will add a nice automation of the status in case the Plex Media Server service dies.

**Comment by EldonMcGuinness** [comment]
I think PRs #2 and #5 address this without the need for PlexPy.

**Comment by ghost** [comment]
Ah okay. Did not see the closed pullrequests
